In [1]:
import numpy as np

c=np.random.randn(5)

In [2]:
print(c)    #this is a "Rank 1 array- this is a very funny D.S . It doesn't behave consistently as either a row vector nor a column vector"

[ 1.26681463 -0.59944006  0.05556821 -2.61900873  0.73904639]


### Don't use these Rank 1 arrays

In [3]:
type(c)

numpy.ndarray

In [4]:
print(c.shape)

(5,)


In [5]:
c=c.reshape(5,1)
c

array([[ 1.26681463],
       [-0.59944006],
       [ 0.05556821],
       [-2.61900873],
       [ 0.73904639]])

In [9]:
b=np.random.randn(1,5)   #row vector
print(b)

[[ 0.96091404  0.74502413  1.07854713 -0.05114677  0.65586579]]


In [11]:
a=np.random.randn(5,1)   #column vector
assert(b.shape==(1,5))    # to make sure it is (1,5) row vector

In [12]:
print(a.T)  #column vector

[[ 0.35004733  0.24201363 -0.02519318  0.355415    0.89118798]]


In [13]:
print(np.dot(a,a.T))

[[ 1.22533135e-01  8.47162246e-02 -8.81880409e-03  1.24412074e-01
   3.11957976e-01]
 [ 8.47162246e-02  5.85705957e-02 -6.09709193e-03  8.60152744e-02
   2.15679636e-01]
 [-8.81880409e-03 -6.09709193e-03  6.34696122e-04 -8.95403280e-03
  -2.24518558e-02]
 [ 1.24412074e-01  8.60152744e-02 -8.95403280e-03  1.26319826e-01
   3.16741581e-01]
 [ 3.11957976e-01  2.15679636e-01 -2.24518558e-02  3.16741581e-01
   7.94216022e-01]]


In [14]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [15]:
c

array([[ 0.00657313,  0.28344995,  0.01449725],
       [ 0.01834474, -0.29507668,  0.28988496],
       [-0.22026468, -0.12575899,  0.2094746 ]])