In [67]:
import numpy as np

c=np.random.randn(5)

In [68]:
print(c)    #this isb a "Rank 1 array- this is a very funny D.S . It doesn't behave consistently as either a row vector nor a column vector"

[-1.00885761  0.57248376  0.61736495 -0.03018744  1.69323835]


### Don't use these Rank 1 arrays

In [69]:
type(c)

numpy.ndarray

In [70]:
print(c.shape)

(5,)


In [71]:
c=c.reshape(5,1)
c

array([[-1.00885761],
       [ 0.57248376],
       [ 0.61736495],
       [-0.03018744],
       [ 1.69323835]])

In [72]:
print(a.T)

[[ 1.33463783 -1.35364718 -0.45363195]
 [ 0.97845298 -1.39825082  0.48781093]
 [ 0.19633623  0.07888393  0.99931022]]


In [39]:
print(np.dot(a,a.T))

7.8281870412525905


In [53]:
a=np.random.randn(5,1)   #column vector
assert(b.shape==(5,1))    # to make sure it is (1,5) row vector

In [54]:
print(a)    

[[ 0.17607296]
 [ 0.52968926]
 [-0.71822001]
 [-0.10520814]
 [ 0.35758708]]


In [55]:
b=np.random.randn(1,5)   #row vector
print(b)

[[ 0.13869162 -0.03414476 -0.34534722  0.53927277  0.26180544]]


In [56]:
print(a.T)  #column vector

[[ 0.17607296  0.52968926 -0.71822001 -0.10520814  0.35758708]]


In [57]:
print(np.dot(a,a.T))

[[ 0.03100169  0.09326395 -0.12645912 -0.01852431  0.06296141]
 [ 0.09326395  0.28057072 -0.38043343 -0.05572762  0.18941004]
 [-0.12645912 -0.38043343  0.51583998  0.07556259 -0.25682619]
 [-0.01852431 -0.05572762  0.07556259  0.01106875 -0.03762107]
 [ 0.06296141  0.18941004 -0.25682619 -0.03762107  0.12786852]]


In [64]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [65]:
c

array([[ 0.18455476,  0.13530124,  0.02714953],
       [-1.88917313, -1.95142272,  0.11009177],
       [-0.31083632,  0.33425634,  0.68474434]])